version: "3.1"

services:
  monguito:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    container_name: mongo_expresss
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@monguito:27017/admin
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongo_data:
